<a href="https://colab.research.google.com/github/Arta-DS/Lin_Alg_HW/blob/main/%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Задание 1**

*   Создайте матрицу 3 на 3, заполненную числами от 1 до 9

*   Прибавьте к ней матрицу с единицами на диагонали

*   Умножьте полученную матрицу на вектор (1, 2, 3)

*   Вычислите транспонированную матрицу от полученной в результате прибавления матрицы

*   Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [25]:
import numpy as np

matrix = np.arange(1, 10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
 matrix_diag = np.eye(3)
 matrix_diag

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
sum_matrix = np.add(matrix, matrix_diag)
sum_matrix

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [28]:
vector = np.array([1, 2, 3])
vector

array([1, 2, 3])

In [29]:
np.dot(sum_matrix, vector)

array([15., 34., 53.])

In [30]:
transpose_matrix = sum_matrix.T
transpose_matrix

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [31]:
inverse_matrix = np.linalg.inv(sum_matrix)
inverse_matrix

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

**Задание 2**

Найдите собственные значения и собственные вектора матрицы:

```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [32]:
m = np.array([[2, 2],
              [1, 3]])

w, v = np.linalg.eig(m)
print ("Матрица A:\n", m)
print ("Собственные числа:\n", w)
print ("Собственные векторы:\n", v)

Матрица A:
 [[2 2]
 [1 3]]
Собственные числа:
 [1. 4.]
Собственные векторы:
 [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


**Задание 3**

Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [23]:
A = np.array([[1, 0], [0, 1]])

# Проверяем определитель
det_A = np.linalg.det(A)
print(det_A)

1.0


In [33]:
det = 0

while det != 1:
    a = np.random.randint(-10,10,(3,3))
    det=np.linalg.det(a)

print('искомая матрица: \n',a)

искомая матрица: 
 [[ 1 -6  2]
 [ 5 -9  2]
 [ 8  2 -3]]
